production:
  type: deploy
  script:
  - set -e; curl -fs -XPOST -d "{\"after\":\"$CI_BUILD_REF\",\"ref\":\"refs/heads/$CI_BUILD_REF_NAME\",\"gitlab\":true}" http://live.leanpoker.org:80/api/tournament/5758fe417b226c0003000003/team/poker-player-raccoon/deploy?secret=$SECRET
